In [60]:
#importing pandas and numpy
import pandas as pd
import numpy as np

In [61]:
# importing data set
df = pd.read_csv('/content/hospital_readmissions_30k.csv')

In [62]:
df.head()

,patient_id,age,gender,blood_pressure,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days
0,1,74,Other,130/72,240,31.5,Yes,No,5,1,Nursing_Facility,Yes
1,2,46,Female,120/92,292,36.3,No,No,4,3,Nursing_Facility,No
2,3,89,Other,135/78,153,30.3,No,Yes,1,1,Home,No
3,4,84,Female,123/80,153,31.5,No,Yes,3,10,Home,No
4,5,32,Other,135/84,205,18.4,No,Yes,6,4,Nursing_Facility,No

In [63]:
# getting the info of the dataset
df.describe()

,patient_id,age,cholesterol,bmi,medication_count,length_of_stay
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,53.884233,225.260400,28.946263,5.012267,5.502900
std,8660.398374,21.056485,43.585671,6.348204,3.166383,2.867298
min,1.000000,18.000000,150.000000,18.000000,0.000000,1.000000
25%,7500.750000,36.000000,188.000000,23.400000,2.000000,3.000000
50%,15000.500000,54.000000,225.000000,28.900000,5.000000,5.000000
75%,22500.250000,72.000000,263.000000,34.500000,8.000000,8.000000
max,30000.000000,90.000000,300.000000,40.000000,10.000000,10.000000

In [64]:
# getting info of the dataset such as null value, datatype, columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   patient_id             30000 non-null  int64
 1   age                    30000 non-null  int64
 2   gender                 30000 non-null  object
 3   blood_pressure         30000 non-null  object
 4   cholesterol            30000 non-null  int64
 5   bmi                    30000 non-null  float64
 6   diabetes               30000 non-null  object
 7   hypertension           30000 non-null  object
 8   medication_count       30000 non-null  int64
 9   length_of_stay         30000 non-null  int64
 10  discharge_destination  30000 non-null  object
 11  readmitted_30_days     30000 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 2.7+ MB

Preprocessing the dataset

In [ ]:
# dropping the column patient_id since we don't need it
df_filter1 = df
df_filter1

,age,gender,blood_pressure,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days
0,74,Other,130/72,240,31.5,Yes,No,5,1,Nursing_Facility,Yes
1,46,Female,120/92,292,36.3,No,No,4,3,Nursing_Facility,No
2,89,Other,135/78,153,30.3,No,Yes,1,1,Home,No
3,84,Female,123/80,153,31.5,No,Yes,3,10,Home,No
4,32,Other,135/84,205,18.4,No,Yes,6,4,Nursing_Facility,No
...,...,...,...,...,...,...,...,...,...,...,...
29995,29,Male,112/80,157,31.4,No,No,4,10,Home,Yes
29996,20,Other,146/83,198,30.2,No,Yes,4,1,Home,Yes
29997,40,Other,131/96,275,23.3,Yes,Yes,7,2,Home,No
29998,61,Other,124/75,232,34.3,No,No,5,3,Home,No
29999,78,Female,148/77,240,35.5,Yes,Yes,2,4,Home,No

In [66]:
# converting the blood pressure column to numerical format
df_filter1[['systole','diastole']] = df_filter1['blood_pressure'].str.split('/',expand = True).astype(float)
df_filter1

,age,gender,blood_pressure,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days,systole,diastole
0,74,Other,130/72,240,31.5,Yes,No,5,1,Nursing_Facility,Yes,130.0,72.0
1,46,Female,120/92,292,36.3,No,No,4,3,Nursing_Facility,No,120.0,92.0
2,89,Other,135/78,153,30.3,No,Yes,1,1,Home,No,135.0,78.0
3,84,Female,123/80,153,31.5,No,Yes,3,10,Home,No,123.0,80.0
4,32,Other,135/84,205,18.4,No,Yes,6,4,Nursing_Facility,No,135.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29,Male,112/80,157,31.4,No,No,4,10,Home,Yes,112.0,80.0
29996,20,Other,146/83,198,30.2,No,Yes,4,1,Home,Yes,146.0,83.0
29997,40,Other,131/96,275,23.3,Yes,Yes,7,2,Home,No,131.0,96.0
29998,61,Other,124/75,232,34.3,No,No,5,3,Home,No,124.0,75.0
29999,78,Female,148/77,240,35.5,Yes,Yes,2,4,Home,No,148.0,77.0

In [67]:
# removing the blood pressure fromm the data frame, since it is of no use
df_filter2 = df_filter1.drop(columns = ['blood_pressure'])
df_filter2

,age,gender,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days,systole,diastole
0,74,Other,240,31.5,Yes,No,5,1,Nursing_Facility,Yes,130.0,72.0
1,46,Female,292,36.3,No,No,4,3,Nursing_Facility,No,120.0,92.0
2,89,Other,153,30.3,No,Yes,1,1,Home,No,135.0,78.0
3,84,Female,153,31.5,No,Yes,3,10,Home,No,123.0,80.0
4,32,Other,205,18.4,No,Yes,6,4,Nursing_Facility,No,135.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29,Male,157,31.4,No,No,4,10,Home,Yes,112.0,80.0
29996,20,Other,198,30.2,No,Yes,4,1,Home,Yes,146.0,83.0
29997,40,Other,275,23.3,Yes,Yes,7,2,Home,No,131.0,96.0
29998,61,Other,232,34.3,No,No,5,3,Home,No,124.0,75.0
29999,78,Female,240,35.5,Yes,Yes,2,4,Home,No,148.0,77.0

In [68]:
# converting the "YES/NO" to the Binary format
cols = ["diabetes","hypertension","readmitted_30_days"]
for col in cols:
  df_filter2[col] = np.where(df_filter2[col]=='Yes',1,0)
df_filter2

,age,gender,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days,systole,diastole
0,74,Other,240,31.5,1,0,5,1,Nursing_Facility,1,130.0,72.0
1,46,Female,292,36.3,0,0,4,3,Nursing_Facility,0,120.0,92.0
2,89,Other,153,30.3,0,1,1,1,Home,0,135.0,78.0
3,84,Female,153,31.5,0,1,3,10,Home,0,123.0,80.0
4,32,Other,205,18.4,0,1,6,4,Nursing_Facility,0,135.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29,Male,157,31.4,0,0,4,10,Home,1,112.0,80.0
29996,20,Other,198,30.2,0,1,4,1,Home,1,146.0,83.0
29997,40,Other,275,23.3,1,1,7,2,Home,0,131.0,96.0
29998,61,Other,232,34.3,0,0,5,3,Home,0,124.0,75.0
29999,78,Female,240,35.5,1,1,2,4,Home,0,148.0,77.0

In [69]:
# one hot encoding to non-binary categorical features with drop_first = True to remove multicollinearity
df_filter3 = pd.get_dummies(df_filter2, columns=['gender', 'discharge_destination'], drop_first=True)
df_filter3

,age,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,readmitted_30_days,systole,diastole,gender_Male,gender_Other,discharge_destination_Nursing_Facility,discharge_destination_Rehab
0,74,240,31.5,1,0,5,1,1,130.0,72.0,False,True,True,False
1,46,292,36.3,0,0,4,3,0,120.0,92.0,False,False,True,False
2,89,153,30.3,0,1,1,1,0,135.0,78.0,False,True,False,False
3,84,153,31.5,0,1,3,10,0,123.0,80.0,False,False,False,False
4,32,205,18.4,0,1,6,4,0,135.0,84.0,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29,157,31.4,0,0,4,10,1,112.0,80.0,True,False,False,False
29996,20,198,30.2,0,1,4,1,1,146.0,83.0,False,True,False,False
29997,40,275,23.3,1,1,7,2,0,131.0,96.0,False,True,False,False
29998,61,232,34.3,0,0,5,3,0,124.0,75.0,False,True,False,False
29999,78,240,35.5,1,1,2,4,0,148.0,77.0,False,False,False,False

In [70]:
# seperating the features(X) and target(y)
X = df_filter3.drop(columns = ['readmitted_30_days'])
y = df_filter3['readmitted_30_days']
X,y

(       age  cholesterol   bmi  diabetes  hypertension  medication_count  \
 0       74          240  31.5         1             0                 5
 1       46          292  36.3         0             0                 4
 2       89          153  30.3         0             1                 1
 3       84          153  31.5         0             1                 3
 4       32          205  18.4         0             1                 6
 ...    ...          ...   ...       ...           ...               ...
 29995   29          157  31.4         0             0                 4
 29996   20          198  30.2         0             1                 4
 29997   40          275  23.3         1             1                 7
 29998   61          232  34.3         0             0                 5
 29999   78          240  35.5         1             1                 2

        length_of_stay  systole  diastole  gender_Male  gender_Other  \
 0                   1    130.0      72.0        False          True
 1                   3    120.0      92.0        False         False
 2                   1    135.0      78.0        False          True
 3                  10    123.0      80.0        False         False
 4                   4    135.0      84.0        False          True
 ...               ...      ...       ...          ...           ...
 29995              10    112.0      80.0         True         False
 29996               1    146.0      83.0        False          True
 29997               2    131.0      96.0        False          True
 29998               3    124.0      75.0        False          True
 29999               4    148.0      77.0        False         False

        discharge_destination_Nursing_Facility  discharge_destination_Rehab
 0                                        True                        False
 1                                        True                        False
 2                                       False                        False
 3                                       False                        False
 4                                        True                        False
 ...                                       ...                          ...
 29995                                   False                        False
 29996                                   False                        False
 29997                                   False                        False
 29998                                   False                        False
 29999                                   False                        False

 [30000 rows x 13 columns],
 0        1
 1        0
 2        0
 3        0
 4        0
         ..
 29995    1
 29996    1
 29997    0
 29998    0
 29999    0
 Name: readmitted_30_days, Length: 30000, dtype: int64)

In [71]:
# splitting the dataset into training and testing dataset with size 0.2

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42,stratify = y)
X_train, X_test, y_train, y_test

(       age  cholesterol   bmi  diabetes  hypertension  medication_count  \
 7445    24          270  23.5         1             1                 1
 28092   21          246  20.4         0             1                 0
 6664    60          253  34.7         1             0                 4
 10741   36          172  36.4         0             1                 7
 86      71          157  34.8         1             0                 7
 ...    ...          ...   ...       ...           ...               ...
 10957   52          184  36.2         1             1                10
 1244    71          243  37.7         0             0                10
 29421   27          189  26.8         1             0                10
 18219   57          280  26.4         1             0                 6
 3232    81          219  22.8         0             1                 0

        length_of_stay  systole  diastole  gender_Male  gender_Other  \
 7445                4    149.0      77.0         True         False
 28092               6    147.0      72.0        False          True
 6664               10    152.0      93.0        False          True
 10741               6    113.0      78.0        False         False
 86                  4    156.0      89.0        False          True
 ...               ...      ...       ...          ...           ...
 10957               6    130.0      81.0        False          True
 1244                9    111.0      96.0        False          True
 29421               5    116.0      90.0        False          True
 18219               1    123.0      80.0        False          True
 3232                6    138.0      87.0        False         False

        discharge_destination_Nursing_Facility  discharge_destination_Rehab
 7445                                    False                         True
 28092                                   False                        False
 6664                                     True                        False
 10741                                   False                        False
 86                                      False                        False
 ...                                       ...                          ...
 10957                                   False                         True
 1244                                    False                        False
 29421                                   False                        False
 18219                                   False                        False
 3232                                    False                        False

 [24000 rows x 13 columns],
        age  cholesterol   bmi  diabetes  hypertension  medication_count  \
 24859   89          233  35.1         1             1                10
 13372   48          271  19.7         0             0                 1
 19829   27          196  29.8         0             1                 7
 5464    62          166  32.4         0             1                 2
 10885   38          273  19.1         1             1                 4
 ...    ...          ...   ...       ...           ...               ...
 6641    55          280  33.2         1             0                 7
 547     53          196  24.8         1             1                 1
 92      89          232  29.7         0             0                10
 24848   36          160  24.1         1             0                 5
 29425   35          208  28.4         1             0                 1

        length_of_stay  systole  diastole  gender_Male  gender_Other  \
 24859               7    130.0      96.0         True         False
 13372               2    128.0      92.0         True         False
 19829               4    136.0      82.0        False          True
 5464                6    136.0      84.0         True         False
 10885               9    126.0      84.0         True         False
 ...               ...      ...       ...          ...           ...
 6641                3    121.0     100.0        False          True
 547                 9    135.0      76.0        False         False
 92                  3    141.0      81.0        False         False
 24848               2    133.0      98.0        False         False
 29425               2    130.0      74.0        False         False

        discharge_destination_Nursing_Facility  discharge_destination_Rehab
 24859                                   False                        False
 13372                                    True                        False
 19829                                   False                        False
 5464                                     True                        False
 10885                                   False                        False
 ...                                       ...                          ...
 6641                                    False                        False
 547                                     False                        False
 92                                      False                        False
 24848                                   False                        False
 29425                                    True                        False

 [6000 rows x 13 columns],
 7445     0
 28092    1
 6664     0
 10741    0
 86       0
         ..
 10957    1
 1244     0
 29421    0
 18219    0
 3232     1
 Name: readmitted_30_days, Length: 24000, dtype: int64,
 24859    0
 13372    0
 19829    0
 5464     0
 10885    0
         ..
 6641     0
 547      1
 92       0
 24848    0
 29425    0
 Name: readmitted_30_days, Length: 6000, dtype: int64)

In [72]:
# feature scaling so that all the features share the similar scales to the training
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [73]:
# importing the model and fitting it
from sklearn.linear_model import LogisticRegression

# Instantiate L2 regularized Logistic Regression model
# penalty='l2' enables Ridge regularization; C=1.0 sets inverse regularization strength
#C controls how harshly the model penalizes large weights. Important: C is the inverse of regularization strength
model = LogisticRegression(penalty='l2', C=1.0, max_iter=1000, random_state=42)

# Train model on scaled features
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [74]:
from sklearn.metrics import roc_auc_score

# Predict probabilities for class 1 (readmitted)
y_probs = model.predict_proba(X_test_scaled)[:, 1]

# Calculate ROC-AUC Score
auc_score = roc_auc_score(y_test, y_probs)
print(f"ROC-AUC Score: {auc_score:.4f}")

ROC-AUC Score: 0.5638